name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: create_file
        run: |
          cat hello.txt
          echo "hello all" >> hello.txt
      - name: upload_file
        uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: hello.txt

  first_demo_job:
    runs-on: ubuntu-latest
    name: Download file
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: hello-artifact
