name: My Demo
on:
  push:
    branches:
      - main
      - fea*

jobs:
  My_Job:
    runs-on: ubuntu-latest
    steps:
#      - name: Simple Echo
#        run: echo "Hello from a job"
      – name: Checkout repository
        uses: actions/checkout@v3
      – name: Read README.md
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      – name: Echo README.md
        run: echo "${{ steps.package.outputs.content }}"
